In [1]:
import numpy as np

In [4]:
a=np.array([1,2,4,5,6])
b=np.array([5,6,7,8,9])
c=np.array([9,10,11,12,12])
d=np.array([10,20])

a+b

array([ 6,  8, 11, 13, 15])

In [3]:
a+c

array([10, 12, 15, 17, 18])

In [5]:
a+d

#ValueError                                Traceback (most recent call last)

#ValueError: operands could not be broadcast together with shapes (5,) (2,) */

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [6]:
a*b

array([ 5, 12, 28, 40, 54])

In [7]:
a/b

array([0.2       , 0.33333333, 0.57142857, 0.625     , 0.66666667])

In [8]:
#scalar multiplcaition

listArray= [1,2,3,4,5]
scalar= 2
mul_scalar_listArray= scalar*listArray;
mul_scalar_listArray;

In [9]:
print(mul_scalar_listArray)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [10]:
npAsArray = np.array(listArray)
vector_scalar_mul= npAsArray*scalar

In [11]:
print(vector_scalar_mul)

[ 2  4  6  8 10]


In [12]:
# Dot vectors of vectors
import numpy as np

In [13]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,10,10,10])
#dot product as a function
# multiplication of 2 values and sum all
np.dot(a,b) 

134

In [14]:
# Basic properties
# communtative = a.b=b.a
np.dot(a,b)
np.dot(b,a)


134

In [15]:
# distributive = a(b+c) =a.b+a.c

np.dot(a,b+c)

304

In [17]:
np.dot(a,b)

134

In [18]:
np.dot(a,c)

170

In [20]:
134+170

304

In [3]:
# Magnitude of a vector = sqrt of sum of square elements
# denoted by vertical bars ||x||
# Norm is used to calculate Magnitude of a vector in numpy
# scalar and vector projection
import numpy as np
from numpy import linalg as lng
a= np.array([10,20,30,40,50])
b= np.array([60,70,80,90,100])
lng.norm(a)
vector_prj_ab= (np.dot(a,b)/np.dot(b,b))*b
print(vector_prj_ab)
print(lng.norm(a))

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]
74.16198487095663


Gausian example and matrix inversion

In [6]:
import numpy as np
A=  np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [7]:
# To calculate the matrix inversion

Ainv = np.linalg.inv(A)
print(Ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
B= np.array([5,11])
print(B)

# x= A-1B
x= np.dot(Ainv,B)
x

[ 5 11]


array([1., 2.])

In [12]:
# cross verify
np.dot(A,x)

array([ 5., 11.])

Inverse and Determinant

In [14]:
import numpy as np

A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [16]:
# Determinant of matrix detA
detA = np.linalg.det(A)
detA

-2.0000000000000004

In [17]:
B= np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [18]:
np.linalg.det(B) 

0.0

In [19]:
# since det(B) is zero matrix inversion not possible
invB = np.linalg.inv(B)
invB

LinAlgError: Singular matrix

In [29]:
# orthogonal- right angle - 
# transpose of matrix - interchanging of rows and columns
# - A.At = I => At = A-1 (A transpose = A inverse)
H = np.array([[1,0],[0,1]])
print(H)

T = np.transpose(H)
print(T)

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [30]:
Hinv = np.linalg.inv(H)
Hinv

array([[1., 0.],
       [0., 1.]])

In [32]:
# Eigen values and Eigen Vectors
# Make ML Learning models because of reduction info
# Ex Application - Recommendation, Financial risk analysis
a= [[2,3],[4,5]]
# eigvalue
EigenValueA = np.linalg.eigvals(a)
print(EigenValueA)
# eigvector
EigenVectorA = np.linalg.eigh(a)
print(EigenVectorA)


[-0.27491722  7.27491722]
(array([-0.77200187,  7.77200187]), array([[-0.82192562,  0.56959484],
       [ 0.56959484,  0.82192562]]))
